project                       = "open-source-apps-001"
project_name                  = "gcp-cloud-sql"
region                        = "europe-west2"
zone                          = "europe-west2-a"
database_password_secret_name = "goose-postgresql-database-password"
environment                   = "production"